export const doctorSpecializations = [
  "Cardiologist",
  "Dermatologist",
  "Neurologist",
  "Pediatrician",
  "Orthopedic Surgeon",
  "Psychiatrist",
  "Gynecologist",
  "Oncologist",
  "Endocrinologist",
  "Gastroenterologist",
  "Ophthalmologist",
  "ENT Specialist",
  "Pulmonologist",
  "Nephrologist",
  "Urologist",
  "Rheumatologist",
  "General Physician",
  "Plastic Surgeon",
  "Dentist",
  "Radiologist",
];

export const doctorQualifications = [
  "MBBS",
  "MD",
  "MS",
  "DM",
  "MCh",
  "BDS",
  "MDS",
  "DNB",
  "PhD",
  "DO (Diploma in Ophthalmology)",
  "DGO (Diploma in Gynecology and Obstetrics)",
  "DLO (Diploma in Otorhinolaryngology)",
  "DA (Diploma in Anesthesiology)",
  "DPM (Diploma in Psychological Medicine)",
  "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
  "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
  "BUMS (Bachelor of Unani Medicine and Surgery)",
  "Fellowship in Cardiology",
  "Fellowship in Oncology",
  "Fellowship in Critical Care",
];
